### ISSUE TITLE
wut is this

### ISSUE THREAD

**Issue by gosoccerboy5** [BarelySmooth/Countdown#2]
what happens on june 24? your birthday? what?

**Comment by BarelySmooth** [comment]
[This](https://www.microsoft.com/en-us/windows/event). I was just excited :P

In the future, I'll probably add a time to choose from. Now, you can see it [here](https://barelysmooth.github.io/Countdown/). I just added the JS files now 🎉

**Comment by gosoccerboy5** [comment]
oh
