### ISSUE TITLE
Some numbers show up as 1 digit

### ISSUE THREAD

**Issue by BarelySmooth** [BarelySmooth/Countdown#3]
Example:
![image](https://user-images.githubusercontent.com/83728060/121765262-b4751800-cb5a-11eb-933b-37a61a92b2f4.png)

**Comment by FunctionalMetatable** [comment]
easy fix: loop through all the numbers, stringify it and check if the length == 1. if so add a zero to the start

**Comment by BarelySmooth** [comment]
> easy fix: loop through all the numbers, stringify it and check if the length == 1. if so add a zero to the start

I was doing that right now 😃
