### ISSUE TITLE
what is this code

### ISSUE THREAD

**Issue by gosoccerboy5** [BarelySmooth/Countdown#6]
ew
https://github.com/BarelySmooth/Countdown/blob/0df78fb592b2443f56ea9935ad3dde71dc7f7055/index.html#L43-L46

**Comment by BarelySmooth** [comment]
Pressing the "x" closes the banner. I used ```display:none;``` to make it look like it was closed

![image](https://user-images.githubusercontent.com/83728060/123133635-fc504500-d460-11eb-8c68-9aa1b6416ef2.png)


![image](https://user-images.githubusercontent.com/83728060/123133482-d32fb480-d460-11eb-9313-b94de5bc1632.png)

**Comment by gosoccerboy5** [comment]
sorry, I meant how terribly the code was formatted 😛

**Comment by BarelySmooth** [comment]
> sorry, I meant how terribly the code was formatted 😛

I didn't notice that lol

Fixed :P
